timeout: 30
triggers:
  - name: pull-request
    type: github_pr
    runs:
      - name: unit-test
        container: golangci/golangci-lint:v1.57
        host-tag: amd64
        script: unit-test
        # unit test needs to run as non-root so that we can test
        # read-only config logic
        container-user: nobody

      - name: lint
        container: golangci/golangci-lint:v1.57
        host-tag: amd64
        script: lint

scripts:

  unit-test: |
    #!/bin/sh -ex
    HOME=/tmp make test

  lint: |
    #!/bin/sh -ex
    make lint
